name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws --version

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region ap-south-1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 050752605875.dkr.ecr.ap-south-1.amazonaws.com

      - name: Pull image from Docker Hub
        run: |
          docker pull harmeet10000/shiksha-dost-backend

      - name: Tag Docker Image for ECR
        run: |
          docker tag harmeet10000/shiksha-dost-backend:latest 050752605875.dkr.ecr.ap-south-1.amazonaws.com/backend/shikshadost-backend:latest

      - name: Push Image to Amazon ECR
        run: |
          docker push 050752605875.dkr.ecr.ap-south-1.amazonaws.com/backend/shikshadost-backend:latest

      - name: Deploy to Amazon ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service \
            --cluster arn:aws:ecs:ap-south-1:050752605875:cluster/ShikshaDost-Backend \
            --service ShikshaDost-Backend-Service \
            --force-new-deployment

      - name: Set Environment Variables for ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecs update-service \
            --cluster arn:aws:ecs:ap-south-1:050752605875:cluster/ShikshaDost-Backend \
            --service ShikshaDost-Backend-Service \
            --force-new-deployment \
            --task-definition ShikshaDost-Backend-Task

      - name: Cleanup local Docker images
        run: |
          docker image prune -f
