name: Deploy Backend to Amazon ECR and ECS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Shiksha-Dost-Backend/**'

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: backend/shikshadost-backend
  ECS_CLUSTER: ShikshaDost-Backend
  DOCKER_HUB_IMAGE: harmeet10000/shiksha-dost-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Shiksha-Dost-Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ env.DOCKER_HUB_IMAGE }} .

    - name: Push image to Docker Hub
      run: docker push ${{ env.DOCKER_HUB_IMAGE }}

    - name: Tag for ECR
      run: |
        docker tag ${{ env.DOCKER_HUB_IMAGE }} ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: Push image to Amazon ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service shikshadost-backend-service \
          --force-new-deployment \
          --region ${{ env.AWS_REGION }}